In [1]:
# import libraries
import numpy as np
from sklearn.impute import SimpleImputer


In [2]:
#create our dataframe
data=[[1,2,np.nan],
      [3,2,np.nan],
      [1,2,3],
      [4,4,5],
      [7,9,567],
      [7,np.nan,4],
      [4,5,np.nan],     
      ]

In [11]:
# apply SimpleImputer to remove nan values
imputed=SimpleImputer(missing_values=np.nan,strategy='mean')
imp=imputed.fit(data)
imputed_data=imp.transform(data)

In [12]:
#print the modifieddata
print(imputed_data)

[[  1.     2.   144.75]
 [  3.     2.   144.75]
 [  1.     2.     3.  ]
 [  4.     4.     5.  ]
 [  7.     9.   567.  ]
 [  7.     4.     4.  ]
 [  4.     5.   144.75]]


In [13]:

#store our new data frame
data=imputed_data

In [14]:
# print the data after modification
print(data)

[[  1.     2.   144.75]
 [  3.     2.   144.75]
 [  1.     2.     3.  ]
 [  4.     4.     5.  ]
 [  7.     9.   567.  ]
 [  7.     4.     4.  ]
 [  4.     5.   144.75]]
