In [1]:
import numpy as np
from sklearn.impute import SimpleImputer


In [2]:
# create a dataframe to work with
data=[[1,2,np.nan],
        [3,np.nan,1],
        [5,np.nan,0],
        [np.nan,4,6 ],
        [5,0,np.nan],
        [4,5,5]]

In [3]:
# apply SimpleImputer to remove nan values
imputed=SimpleImputer(missing_values=np.nan, strategy='median')
imp=imputed.fit(data)
imputed_data=imp.transform(data)

In [4]:
#print the modified data
print(imputed_data)

[[1. 2. 3.]
 [3. 3. 1.]
 [5. 3. 0.]
 [4. 4. 6.]
 [5. 0. 3.]
 [4. 5. 5.]]


In [5]:
#store our new data frame
data=imputed_data

In [6]:
# print the data after modification
print (data)

[[1. 2. 3.]
 [3. 3. 1.]
 [5. 3. 0.]
 [4. 4. 6.]
 [5. 0. 3.]
 [4. 5. 5.]]
